### PERTEMUAN 2


In [7]:
import numpy as np

#### Dictionary


In [1]:
my_dict = {"0": 0, "1": 1, "2": 2, "3": 3, "4": 4}
print(my_dict)
print(my_dict.values())

{'0': 0, '1': 1, '2': 2, '3': 3, '4': 4}
dict_values([0, 1, 2, 3, 4])


In [5]:
me = {"name": "James", "age": 39, "Jobs": ["Programmer", "Teacher"]}
print(me)
print(me["Jobs"])
print(me["age"])
print(me.keys())

{'name': 'James', 'age': 39, 'Jobs': ['Programmer', 'Teacher']}
['Programmer', 'Teacher']
39
dict_keys(['name', 'age', 'Jobs'])


#### NumPy

In [6]:
x = [list(range(5)) for N in range(5)]
x[2][3]

3

#### NumPy Array

In [8]:
my_array = np.array(range(5))
print(my_array)
print(my_array[3])

[0 1 2 3 4]
3


In [9]:
for element in my_array:
    print("Hello" * element)


Hello
HelloHello
HelloHelloHello
HelloHelloHelloHello


In [12]:
big_list = range(10000)
big_array = np.arange(10000)
big_array

array([   0,    1,    2, ..., 9997, 9998, 9999], shape=(10000,))

#### Multi-Dimensional Array

In [16]:
x = np.array(range(40))
y = x.reshape([4, 5, 2])  # 4 Arrays - 5 Rows - 2 Columns
y

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]],

       [[30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39]]])

In [20]:
print(y[3][2][1])

35


In [22]:
print(y.shape)
print(y.transpose().shape)  # 2 Arrays - 5 Rows - 4 Columns

(4, 5, 2)
(2, 5, 4)


#### Function


##### 1. Default Parameters

##### 2. Early Return

##### 3. Scooping

##### 4. Side Effects

##### 5. Unpacking Arguments

##### 6. Sequence Argument

In [35]:
def doubler(*sequence):
    return [x * 2 for x in sequence]
print(doubler(1, 2, 3, 4, 5))

[2, 4, 6, 8, 10]


In [36]:
doubler(5, 2, "Wow!")

[10, 4, 'Wow!Wow!']

##### 7. Keyword Argument

In [37]:
def arrowify(**args):
    for key, value in args.items():
        print(key + " -> " + value)


arrowify(neutron="n", proton="p", electron="e")

neutron -> n
proton -> p
electron -> e


In [38]:
def somefunc(a, b, *args, **kwargs):
    print("A:", a)
    print("B:", b)
    print("args:", args)
    print("keyword args", kwargs)
somefunc(1, 2, 3, 4, 5, fish="James")

A: 1
B: 2
args: (3, 4, 5)
keyword args {'fish': 'James'}
